---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Configure MySQL to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL

- name: Ensure MySQL is enabled and started
  systemd:
    name: mysql
    enabled: yes
    state: started

- name: Create database and user
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present

- name: Import database schema
  mysql_db:
    name: "{{ db_name }}"
    state: import
    target: "{{ mysql_path }}"
  become: yes

handlers:
  - name: Restart MySQL
    systemd:
      name: mysql
      state: restarted
